name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install codespell
        run: python -m pip install codespell

      - name: Run Spellcheck 
        run: |
          git ls-files '*.md' | xargs grep -Eni --color=always "\b[A-Z]{2,}\b" |& \
            if grep -vq "^Binary file" ; then \
              grep -vE "\b[A-Z]{2,}\b" ; \
              exit 1 ; \
            fi
