# Actions workflow to check for grammar/spelling mistakes. False alarms may be triggered by certain words like boardnames, abbreviations, and the likes.

name: Spell Check

on:
  push:
    branches:
      - main

jobs:
  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run spell check
        run: |
          # Ignore specific files
          IGNORE_FILES="supported-devices.md terminology.md"
          FILE_LIST=$(find docs -name "*.md" -not -name "$IGNORE_FILES" -type f)
          
          # Run spell check on each file
          for FILE in $FILE_LIST; do
            npx markdown-spellcheck $FILE
          done
