name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Aspell
        run: sudo apt-get install aspell -y

      - name: Install dictionaries
        run: sudo apt-get install aspell-en -y

      - name: List Markdown Files
        run: |
          find . -name "*.md" -type f -print > filelist.txt

      - name: Run Spell Check
        run: |
          cat filelist.txt | xargs -I % sh -c "aspell --lang=en --mode=markdown --personal=.aspell.en.pws -c %" || true
