# Actions workflow to check for grammar/spelling mistakes. False alarms may be triggered by certain words like boardnames, abbreviations, and the likes.

name: Spell Check

on:
  push:
    branches:
      - main

jobs:
  spell_check:
    name: Spell Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run spell check
        run: |
          cd docs
          npx markdown-spellcheck --ignore "supported-devices.md,terminology.md" --report '**/*.md'
