# Actions workflow to check for grammar/spelling mistakes. False alarms may be triggered by certain words like boardnames, abbreviations, and the likes.

name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cSpell
        run: npm install -g cspell

      - name: Run spell check
        run: cspell "**/*.md"

