name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: sudo apt-get install pandoc -y

      - name: Extract Plain Text
        run: |
          find . -name "*.md" -type f -exec sh -c 'pandoc -f markdown -t plain "$0" -o "${0%.*}.txt"' {} \;

      - name: Run Spell Check
        run: |
          git ls-files '*.txt' | xargs grep -Eni --color=always "\b[A-Z]{2,}\b" |& \
            if grep -vq "^Binary file" ; then \
              grep -vE "\b[A-Z]{2,}\b" ; \
              exit 1 ; \
            fi
