# Actions workflow to check for grammar/spelling mistakes. False alarms may be triggered by certain words like boardnames, abbreviations, and the likes.

name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Spell Check
        run: |
          markdown_files=$(find docs -name "*.md")
          echo "$markdown_files" | xargs -I{} npx cspell "{}" 

