# Actions workflow to check for grammar/spelling mistakes. False alarms may be triggered by certain words like boardnames, abbreviations, and the likes.

name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spell_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cSpell
        run: npm install -g cspell

      - name: Generate code names list
        id: generate_code_names
        run: |
          code_names=$(grep -Eo '[A-Z]{2,}' *.md)
          echo "::set-output name=code_names::$code_names"

      - name: Run spell check
        run: |
          code_names=${{ steps.generate_code_names.outputs.code_names }}
          cspell "**/*.md" --ignore "$code_names"
